import './globals.css'
import { Inter } from 'next/font/google'
import { Notification } from './components/Notification'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Livekit Conference Demo App',
  description: 'Generated by create next app',
}

export default function RootLayout(/** @type {React.PropsWithChildren} */{ children }) {
  return (
    <html lang="en" data-theme='light'>
      <body className={inter.className}>
        {children}
        <Notification />
      </body>
    </html>
  )
}
